### ISSUE TITLE
Documentation mentions cruise-config.xml, but doesn't specify its location

### ISSUE THREAD

**Issue by BurkovBA** [gocd/docs.go.cd#143]
I'm reading through the documentation of GoCD installation on Linux: https://docs.gocd.org/current/installation/install/server/linux.html#copying-existing-config-to-a-new-gocd-server-instance

It nicely enumerates a set of configuration files, which does not include `cruise-config.xml`: https://docs.gocd.org/current/installation/install/server/linux.html#location-of-gocd-server-files.

Then in the next paragraph, `cruise-config.xml` suddenly comes up out of nowhere, and it's never mentioned, where it is located: https://docs.gocd.org/current/installation/install/server/linux.html#copying-existing-config-to-a-new-gocd-server-instance.

Please, improve your (otherwise very beautiful and user-friendly) documentation.

Thank you!

**Comment by arvindsv** [comment]
@BurkovBA makes sense. Do you mind opening a PR and making that change [here](https://github.com/gocd/docs.go.cd/blame/master/installation/install/server/linux.md#L59)? This would break a pattern though, since `/etc/go` is already mentioned. I think it's fine to mention `cruise-config.xml` too.

You'll also need to sign the CLA, as a one-time activity. Once you submit the PR, the CLA bot should send you a link. Thank you!

**Comment by BurkovBA** [comment]
@arvindsv 

Sure, I'll make a PR later today. Will try to make it as consistent with the rest of documentation as possible. Will sign CLA as well. Cheers!

**Comment by arvindsv** [comment]
Closing because of your PR, https://github.com/gocd/docs.go.cd/pull/144. Thank you, @BurkovBA.
