### ISSUE TITLE
Go agent 19.4 with openjdk 12 issue

### ISSUE THREAD

**Issue by david-77** [gocd/docs.go.cd#316]
Hi,

I installed a new agent on a server with the latest version available (19.4.0 Windows).
Installation was ok, but I did not achieve to see the new agent on my GoCD Server (19.1 Windows).
After some investigation, I saw this error in "go-agent-stderr" log file : 

> 
> 2019-06-04 11:26:36,658 - [Tue Jun 04 11:26:36 CEST 2019] Starting process: 
> 2019-06-04 11:26:36,658 - [Tue Jun 04 11:26:36 CEST 2019]   Working directory    : D:\Program Files (x86)\Go Agent
> 2019-06-04 11:26:36,658 - [Tue Jun 04 11:26:36 CEST 2019]   Application arguments: [-serverUrl, https://172.XXX.XXX.XX:8154/go, -sslVerificationMode, NONE]
> 2019-06-04 11:26:36,658 - [Tue Jun 04 11:26:36 CEST 2019]            GoCD Version: 19.1.0-8469
> 2019-06-04 11:26:37,627 - Running GoCD requires Java version >= VERSION_1_8 and <= 11. You are currently running with Java version 12. GoCD will now exit!

I could see the openjdk version packaged with the agent is 12.0X. I checked on my previous installation agent 19.2, i got a openjdk version 11.
Either the agent source code is incorrect and it should let the use of java 12, or the jdk packaged should be changed to java 11.

**Comment by arvindsv** [comment]
@david-77 Is this the setup you have?
- Your GoCD server is a 19.1 server.
- Your installed GoCD agent, called bootstrapper, is a 19.4 bootstrapper.

Typically, a newer agent is not guaranteed to work. An older agent should be fine. However, in this case, it looks like this is a different problem: Since the GoCD bootstrapper is from 19.4, it is bundled with Java 12. However, since the server is a 19.1, the bootstrapper downloads a 19.1 agent from the GoCD server. That 19.1 agent works with Java 8 to Java 11.

In this case you'll either need to install a 19.1 GoCD agent or provide the GoCD agent with a Java version less than 12.


I don't think the packaging is wrong, because the 19.4 GoCD agent is supposed to be used with a 19.4 or newer GoCD server. A 19.4 GoCD server (on Windows) will be bundled with Java 12.

**Comment by david-77** [comment]
Yes Arvindsv, my setup is as you described.
The mismactch between server and agent was my first thought, but why in this case I retrieve an java version problem in agent log ? 
The server and the agent can work in different java version, can't they ? 
I mean I suppose that both are communicating on  a standard communication (rest/soap).
But maybe I'm wrong and they are using some java dedicated protocol which could produce this king of message on the agent side.

**Comment by arvindsv** [comment]
>  The server and the agent can work in different java version, can't they?  I mean I suppose that both are communicating on a standard communication (rest/soap).

Yes, they can be on different Java versions.

Let me explain a little bit more. The different pieces are:

- GoCD Agent Bootstrapper is what you install. Its job is to download an appropriate agent and agent launcher using the GoCD server. You installed a 19.4 bootstrapper which comes with Java 12.

- GoCD Agent Launcher: Downloaded by the bootstrapper, from the GoCD server. The launcher knows how to launch an agent.

- GoCD Agent: The agent downloaded by the bootstrapper, from the GoCD server. It knows how to run jobs, etc.

- GoCD server: You already know this. You have a 19.1 server, which supports up to Java 11.

<hr>

1. You pointed the 19.4 bootstrapper to a 19.1 server. 19.1 server has a 19.1 agent and launcher, which works only on Java 11.

2. The 19.4 bootstrapper downloads the 19.1 agent and launcher from the server and runs them using: `java -jar` (using Java 12).

3. When the agent or launcher launches, it checks which version of Java it is running with and errors out, since it is running on an unsupported version of Java.

You can see the [code for 19.1](https://github.com/gocd/gocd/blob/19.1.0/base/src/main/java/com/thoughtworks/go/utils/AssertJava8.java#L24-L29) and the [corresponding code for 19.4](https://github.com/gocd/gocd/blob/19.4.0/base/src/main/java/com/thoughtworks/go/utils/AssertJava8.java#L24-L29).

In that sense, this is not a Java mismatch between the agent and the server. It's just that the 19.1 agent, which is really what you're running (not 19.4), does not support Java 12.

To be very clear: If your server was running on Java 10 and your agent was running on Java 11 (or whatever is supported by them), then it'll work fine.

<hr>

As an aside: Because of recent Java licensing changes, and how they're planning to keep releasing new versions of Java every 6 months, this might show up more. We wrote [a blog post about how we plan to handle Java versioning](https://www.gocd.org/2019/05/21/official-stance-on-java/).

**Comment by david-77** [comment]
OK thanks a lot Arvindsv for this answer, this is very complete !
The situation is clear now. For the moment, i will keep my go server version and install a previous version of the bootstrapper.
Thanks again ;)
