### ISSUE TITLE
sidebar feels jumpy when expanding a sidebar section

### ISSUE THREAD

**Issue by ketan** [gocd/docs.go.cd#330]
When expanding a sidebar section, other sidebar sections are forced to collapse, this causes your mouse to hover on a link it was not hovering on before. I was taken aback and almost got confused if I did something wrong when I noticed this behavior.

![sidebar](https://user-images.githubusercontent.com/10598/59819176-64389600-9344-11e9-9f23-09131d5b86a2.gif)

**Comment by arvindsv** [comment]
Makes sense. Fixing.

**Comment by arvindsv** [comment]
Fixed in https://github.com/gocd/docs.go.cd/commit/68c518262c101bc293b3ae709f5736fabe61f620

@ketan Can you check on https://docs.gocd.org/19.6.0/ and close this issue if you consider it fixed? It's now a normal menu where it does not automatically close anything. You can have multiple menu items open.

**Comment by ketan** [comment]
Works as expected. Closing.
