### ISSUE TITLE
gocd on kubernetes plugin reinstall

### ISSUE THREAD

**Issue by charlesguo404** [gocd/docs.go.cd#381]
The plugin will be re-downloaded whenever the goserver pod is restarted,
Can't add a test in install script? When the plugin exists, it will not be downloaded again

**Comment by varshavaradarajan** [comment]
This is a result of https://github.com/gocd/docker-gocd-server/blame/master/install-gocd-plugins#L23.

We decided to always download the plugin jar because a new download url could be provided for the same environment variable to download a new version of the same plugin.  

The case of pod reschedules resulting in repeatedly downloading the jar is valid, but less likely because we expect a Kubernetes setup to be resilient. But, maybe, we could introduce an option not to overwrite. @ketan, @gocd/committers - WDYT?

**Comment by charlesguo404** [comment]
@varshavaradarajan 
You know that in some intranet environments, we don't need to update the plugin in time, and there is no way to download the plugin directly to gitlab. We need to update the plugin when we need it. If need to download the plugin every time when restart and the download overwrite the original download every time, it will affect the user's use.

**Comment by arvindsv** [comment]
I can understand wanting to make this optional.
